[book]
authors = ["Thomas"]
language = "en"
multilingual = false
src = "book"
title = "expression_parser"

[rust]
edition = "2018"

[build]
build-dir = "docs"


[output.html]
additional-js = ["book/custom.js"]
